CREATE TABLE reconnaissound_playlists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid INTEGER REFERENCES reconnaissound_users(id) ON DELETE CASCADE NOT NULL,
    videoid TEXT NOT NULL,
    videotitle TEXT NOT NULL
);